feat: created isPalindrome function, minNum, maxNum functions, and re…
LudmilaZhuleha/if-js pull request #3
Opened 2022-05-04 13:49 UTC by LudmilaZhuleha

2022-05-04 15:18 UTC, Marinarium requested changes

2022-05-04 15:18 UTC, Marinarium commented on src/main.js
> +// }
Please, put it in another file or delete(your work will save on lesson-2 branch), don't leave an unused code=)

2022-05-04 15:18 UTC, Marinarium commented on src/main.js
> +  restNumbers[9] = Math.floor(Math.random() * 100);
try to do your code shorter
[DRY](https://www.youtube.com/watch?v=NWemqNMCesQ&ab_channel=SergeyNemchinskiy) 
![image](https://user-images.githubusercontent.com/25488411/166711599-bbe7c4bd-a614-4693-a244-2557dc079aa3.png)
[and more](https://www.fullstackguy.ru/blog/2022/04/dry-principle/)

2022-05-04 15:18 UTC, Marinarium commented on src/main.js
> +  return arrayResult;
your code doesn;t work with 100.  it should be 1zerozero

напишите функцию, которая будет заменять все 0 на строку 'zero';

how about a challange?) try to create such a function, that will be work even with 207 => '2zero7' =)

2022-05-05 10:08 UTC, LudmilaZhuleha commented on src/main.js
> +// }
Done.

2022-05-05 10:09 UTC, LudmilaZhuleha commented on src/main.js
> +  restNumbers[9] = Math.floor(Math.random() * 100);
Done using ...Array().map()

2022-05-05 10:16 UTC, LudmilaZhuleha commented on src/main.js
> +  return arrayResult;
Done.
Initial solution was with replace() method, with replace only the first entry. 
Final solution uses check for entries (includes()) and replaceAll() method replacing all the entries being found.

2022-05-05 16:27 UTC, merged